
spring:
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    flyway:
        baseline-on-migrate: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
