
#spring:
 #   jpa:
  #      database: postgresql
   #     show-sql: true
    #    hibernate:
     #       ddl-auto: create-drop
    #datasource:
     #   driver-class-name: org.postgresql.Driver
      #  url: jdbc:postgresql://localhost:5432/postgres
       # username: postgres
        #password: postgres
   # flyway:
    #    baseline-on-migrate: true
   # mvc:
    #    pathmatch:
     #        matching-strategy: ant_path_matcher
      #  view:
       #     prefix: /WEB-INF/jsp/
        #    suffix: .jsp

spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    flyway:
        enabled: false
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

